[versions]
agp = "8.5.2"
kotlin = "1.9.0"
coreKtx = "1.13.0"
lifecycleRuntimeKtx = "2.8.5"
appcompat = "1.7.0"
jetbrainsKotlinJvm = "1.9.25"
symbolProcessingApi = "2.0.10-1.0.24"
ksp = "1.9.0-1.0.11"
kotlinpoetKsp = "1.18.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "symbolProcessingApi" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoetKsp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
jetbrains-kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }